; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --start-before=ir-translator --stop-after=ir-translator %s -o - | FileCheck %s

define void @arg_0() {
  ; CHECK-LABEL: name: arg_0
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   POP 0, 0
  ret void
}

define void @arg_64(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64,
  ; CHECK-LABEL: name: arg_64
  ; CHECK: bb.1 (%ir-block.16):
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8, $r9, $r10, $r11, $r12, $r13, $r14, $r15, $r254
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s64) = COPY $r2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s64) = COPY $r3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s64) = COPY $r4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s64) = COPY $r5
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s64) = COPY $r6
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s64) = COPY $r7
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s64) = COPY $r8
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(s64) = COPY $r9
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:_(s64) = COPY $r10
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:_(s64) = COPY $r11
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:_(s64) = COPY $r12
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:_(s64) = COPY $r13
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:_(s64) = COPY $r14
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:_(s64) = COPY $r15
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:_(p0) = COPY $r254
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY16]], [[C]](s64)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from stack, align 1)
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:_(p0) = COPY $r254
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 8
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY17]], [[C1]](s64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD1]](p0) :: (load (s64) from stack + 8, align 1)
  ; CHECK-NEXT:   POP 0, 0
  i64 %stack0, i64 %stack1) {
  ret void
}
