; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=mmix --enable-new-pm --start-before=ir-translator --stop-after=ir-translator %s -o - | FileCheck %s

define i128 @ret_i128() {
  ; CHECK-LABEL: name: ret_i128
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s128) = G_CONSTANT i128 255
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C]](s128)
  ; CHECK-NEXT:   $r0 = COPY [[UV]](s64)
  ; CHECK-NEXT:   $r1 = COPY [[UV1]](s64)
  ; CHECK-NEXT:   POP 2, 0
  ret i128 255
}

define ptr @ret_ptr() {
  ; CHECK-LABEL: name: ret_ptr
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; CHECK-NEXT:   $r0 = COPY [[C]](p0)
  ; CHECK-NEXT:   POP 1, 0
  ret ptr null
}

define void @ret_void() {
  ; CHECK-LABEL: name: ret_void
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   POP 0, 0
  ret void
}
