; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --stop-after=instruction-select %s -o - | FileCheck %s

define i64 @selectG_CONSTANT() {
  ; CHECK-LABEL: name: selectG_CONSTANT
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETH:%[0-9]+]]:gpr = SETH 40503
  ; CHECK-NEXT:   [[ORMH:%[0-9]+]]:gpr = ORMH killed [[SETH]], 31161
  ; CHECK-NEXT:   [[ORML:%[0-9]+]]:gpr = ORML killed [[ORMH]], 32586
  ; CHECK-NEXT:   [[ORL:%[0-9]+]]:gpr = ORL killed [[ORML]], 31765
  ; CHECK-NEXT:   $r0 = COPY [[ORL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret i64 11400714819323198485
}

define double @selectG_FCONSTANT() {
  ; CHECK-LABEL: name: selectG_FCONSTANT
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETH:%[0-9]+]]:gpr = SETH 16393
  ; CHECK-NEXT:   [[ORMH:%[0-9]+]]:gpr = ORMH killed [[SETH]], 8699
  ; CHECK-NEXT:   [[ORML:%[0-9]+]]:gpr = ORML killed [[ORMH]], 21572
  ; CHECK-NEXT:   [[ORL:%[0-9]+]]:gpr = ORL killed [[ORML]], 11544
  ; CHECK-NEXT:   $r0 = COPY [[ORL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret double f0x400921FB54442D18 ; return \pi
}

define i8 @selectG_LOAD_i8(ptr %p) {
  ; CHECK-LABEL: name: selectG_LOAD_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[LDBI:%[0-9]+]]:gpr = LDBI [[COPY]], 0 :: (load (s8) from %ir.p)
  ; CHECK-NEXT:   $r0 = COPY [[LDBI]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %v = load i8, ptr %p, align 1
  ret i8 %v
}

define i16 @selectG_LOAD_i16(ptr %p) {
  ; CHECK-LABEL: name: selectG_LOAD_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[LDWI:%[0-9]+]]:gpr = LDWI [[COPY]], 0 :: (load (s16) from %ir.p)
  ; CHECK-NEXT:   $r0 = COPY [[LDWI]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %v = load i16, ptr %p, align 2
  ret i16 %v
}

define i32 @selectG_LOAD_i32(ptr %p) {
  ; CHECK-LABEL: name: selectG_LOAD_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[LDTI:%[0-9]+]]:gpr = LDTI [[COPY]], 0 :: (load (s32) from %ir.p)
  ; CHECK-NEXT:   $r0 = COPY [[LDTI]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %v = load i32, ptr %p, align 4
  ret i32 %v
}

define i64 @selectG_LOAD_i64(ptr %p) {
  ; CHECK-LABEL: name: selectG_LOAD_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[LDOI:%[0-9]+]]:gpr = LDOI [[COPY]], 0 :: (load (s64) from %ir.p)
  ; CHECK-NEXT:   $r0 = COPY [[LDOI]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %v = load i64, ptr %p, align 8
  ret i64 %v
}

define i64 @selectG_UCMP(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: selectG_UCMP
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; CHECK-NEXT:   [[CMPU:%[0-9]+]]:gpr = CMPU [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $r0 = COPY [[CMPU]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %v = call i64 @llvm.ucmp(i64 %a, i64 %b)
  ret i64 %v
}
