; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --stop-after=instruction-select %s -o - | FileCheck %s

define i64 @ret_0() {
  ; CHECK-LABEL: name: ret_0
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETL:%[0-9]+]]:gpr = SETL 0
  ; CHECK-NEXT:   $r0 = COPY [[SETL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret i64 0
}

define i64 @ret_281483566841860() {
  ; CHECK-LABEL: name: ret_281483566841860
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETH:%[0-9]+]]:gpr = SETH 1
  ; CHECK-NEXT:   [[ORMH:%[0-9]+]]:gpr = ORMH killed [[SETH]], 2
  ; CHECK-NEXT:   [[ORML:%[0-9]+]]:gpr = ORML killed [[ORMH]], 3
  ; CHECK-NEXT:   [[ORL:%[0-9]+]]:gpr = ORL killed [[ORML]], 4
  ; CHECK-NEXT:   $r0 = COPY [[ORL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret i64 281483566841860
}

define i64 @ret_8590131204() {
  ; CHECK-LABEL: name: ret_8590131204
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETMH:%[0-9]+]]:gpr = SETMH 2
  ; CHECK-NEXT:   [[ORML:%[0-9]+]]:gpr = ORML killed [[SETMH]], 3
  ; CHECK-NEXT:   [[ORL:%[0-9]+]]:gpr = ORL killed [[ORML]], 4
  ; CHECK-NEXT:   $r0 = COPY [[ORL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret i64 8590131204
}

define i64 @ret_281483566645252() {
  ; CHECK-LABEL: name: ret_281483566645252
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[SETH:%[0-9]+]]:gpr = SETH 1
  ; CHECK-NEXT:   [[ORMH:%[0-9]+]]:gpr = ORMH killed [[SETH]], 2
  ; CHECK-NEXT:   [[ORL:%[0-9]+]]:gpr = ORL killed [[ORMH]], 4
  ; CHECK-NEXT:   $r0 = COPY [[ORL]]
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  ret i64 281483566645252
}
