; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --stop-after=legalizer %s -o - | FileCheck %s

define i63 @addi63(i63 %a, i63 %b) {
  ; CHECK-LABEL: name: addi63
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $r0 = COPY [[ADD]](s64)
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %s = add i63 %a, %b
  ret i63 %s
}

define i130 @addi130(i130 %a, i130 %b) {
  ; CHECK-LABEL: name: addi130
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2, $r3, $r4, $r5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s64) = COPY $r5
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s64) = COPY $r4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s64) = COPY $r3
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[COPY3]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[COPY3]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[COPY1]], [[COPY4]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD1]](s64), [[COPY1]]
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:_(s64) = G_AND [[ICMP]], [[C]]
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:_(s64) = G_ADD [[ADD1]], [[AND]]
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(s64) = G_ICMP intpred(eq), [[ADD2]](s64), [[C1]]
  ; CHECK-NEXT:   [[AND1:%[0-9]+]]:_(s64) = G_AND [[ICMP2]], [[ICMP]]
  ; CHECK-NEXT:   [[OR:%[0-9]+]]:_(s64) = G_OR [[ICMP1]], [[AND1]]
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s64) = COPY [[ADD2]](s64)
  ; CHECK-NEXT:   [[ADD3:%[0-9]+]]:_(s64) = G_ADD [[COPY2]], [[COPY5]]
  ; CHECK-NEXT:   [[AND2:%[0-9]+]]:_(s64) = G_AND [[OR]], [[C]]
  ; CHECK-NEXT:   [[ADD4:%[0-9]+]]:_(s64) = G_ADD [[ADD3]], [[AND2]]
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(s64) = COPY [[ADD4]](s64)
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:_(p0) = COPY $r254
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY9]], [[C1]](s64)
  ; CHECK-NEXT:   G_STORE [[COPY6]](s64), [[PTR_ADD]](p0) :: (store (s64) into stack, align 1)
  ; CHECK-NEXT:   $r0 = COPY [[COPY7]](s64)
  ; CHECK-NEXT:   $r1 = COPY [[COPY8]](s64)
  ; CHECK-NEXT:   POP 2, 0, implicit $r0, implicit $r1
  %s = add i130 %a, %b
  ret i130 %s
}
