; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --stop-after=legalizer %s -o - | FileCheck %s

define i1 @fcmp_ogt(double %a, double %b) {
  ; CHECK-LABEL: name: fcmp_ogt
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[FCMP:%[0-9]+]]:_(s64) = G_FCMP floatpred(uno), [[COPY]](s64), [[COPY1]]
  ; CHECK-NEXT:   G_BRCOND [[FCMP]](s64), %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[3WAY_FCMP:%[0-9]+]]:_(s64) = G_3WAY_FCMP [[COPY]](s64), [[COPY1]]
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 2
  ; CHECK-NEXT:   [[SELECT_IF:%[0-9]+]]:_(s64) = G_SELECT_IF [[C2]](s64), [[3WAY_FCMP]](s64), [[C1]], [[C]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (%ir-block.0):
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s64) = G_PHI [[FCMP]](s64), %bb.1, [[SELECT_IF]](s64), %bb.3
  ; CHECK-NEXT:   $r0 = COPY [[PHI]](s64)
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %s = fcmp ogt double %a, %b
  ret i1 %s
}

define i1 @fcmp_ugt(double %a, double %b) {
  ; CHECK-LABEL: name: fcmp_ugt
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[FCMP:%[0-9]+]]:_(s64) = G_FCMP floatpred(uno), [[COPY]](s64), [[COPY1]]
  ; CHECK-NEXT:   G_BRCOND [[FCMP]](s64), %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[3WAY_FCMP:%[0-9]+]]:_(s64) = G_3WAY_FCMP [[COPY]](s64), [[COPY1]]
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 2
  ; CHECK-NEXT:   [[SELECT_IF:%[0-9]+]]:_(s64) = G_SELECT_IF [[C2]](s64), [[3WAY_FCMP]](s64), [[C1]], [[C]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (%ir-block.0):
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s64) = G_PHI [[FCMP]](s64), %bb.1, [[SELECT_IF]](s64), %bb.3
  ; CHECK-NEXT:   $r0 = COPY [[PHI]](s64)
  ; CHECK-NEXT:   POP 1, 0, implicit $r0
  %s = fcmp ugt double %a, %b
  ret i1 %s
}
