; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mmix --enable-new-pm --stop-after=legalizer %s -o - | FileCheck %s

define i130 @mul130(i130 %a, i130 %b) {
  ; CHECK-LABEL: name: mul130
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2, $r3, $r4, $r5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $r2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $r1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s64) = COPY $r0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s64) = COPY $r5
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s64) = COPY $r4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s64) = COPY $r3
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY3]]
  ; CHECK-NEXT:   [[UMULH:%[0-9]+]]:_(s64) = G_UMULH [[COPY]], [[COPY3]]
  ; CHECK-NEXT:   [[MUL1:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY4]]
  ; CHECK-NEXT:   [[MUL2:%[0-9]+]]:_(s64) = G_MUL [[COPY1]], [[COPY3]]
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[UMULH]], [[MUL1]]
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD]](s64), [[MUL1]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(s64) = COPY [[ADD]](s64)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-NEXT:   [[AND:%[0-9]+]]:_(s64) = G_AND [[ICMP]], [[C]]
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s64) = G_ADD [[COPY6]], [[MUL2]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(s64) = G_ICMP intpred(ult), [[ADD1]](s64), [[MUL2]]
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(s64) = COPY [[ADD1]](s64)
  ; CHECK-NEXT:   [[AND1:%[0-9]+]]:_(s64) = G_AND [[ICMP1]], [[C]]
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:_(s64) = G_ADD [[AND]], [[AND1]]
  ; CHECK-NEXT:   [[UMULH1:%[0-9]+]]:_(s64) = G_UMULH [[COPY1]], [[COPY3]]
  ; CHECK-NEXT:   [[UMULH2:%[0-9]+]]:_(s64) = G_UMULH [[COPY]], [[COPY4]]
  ; CHECK-NEXT:   [[MUL3:%[0-9]+]]:_(s64) = G_MUL [[COPY]], [[COPY5]]
  ; CHECK-NEXT:   [[MUL4:%[0-9]+]]:_(s64) = G_MUL [[COPY1]], [[COPY4]]
  ; CHECK-NEXT:   [[MUL5:%[0-9]+]]:_(s64) = G_MUL [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   [[ADD3:%[0-9]+]]:_(s64) = G_ADD [[UMULH1]], [[UMULH2]]
  ; CHECK-NEXT:   [[ADD4:%[0-9]+]]:_(s64) = G_ADD [[ADD3]], [[MUL3]]
  ; CHECK-NEXT:   [[ADD5:%[0-9]+]]:_(s64) = G_ADD [[ADD4]], [[MUL4]]
  ; CHECK-NEXT:   [[ADD6:%[0-9]+]]:_(s64) = G_ADD [[ADD5]], [[MUL5]]
  ; CHECK-NEXT:   [[ADD7:%[0-9]+]]:_(s64) = G_ADD [[ADD6]], [[ADD2]]
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(p0) = COPY $r254
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY8]], [[C1]](s64)
  ; CHECK-NEXT:   G_STORE [[MUL]](s64), [[PTR_ADD]](p0) :: (store (s64) into stack, align 1)
  ; CHECK-NEXT:   $r0 = COPY [[COPY7]](s64)
  ; CHECK-NEXT:   $r1 = COPY [[ADD7]](s64)
  ; CHECK-NEXT:   POP 2, 0, implicit $r0, implicit $r1
  %s = mul i130 %a, %b
  ret i130 %s
}
