#ifndef LLVM_TOOLS_LLVM_MMIXWARE_LLVM_MMIX_SIMCONFIG_H
#define LLVM_TOOLS_LLVM_MMIXWARE_LLVM_MMIX_SIMCONFIG_H

namespace mmix {

struct SimConfig {

};

}

#endif // LLVM_TOOLS_LLVM_MMIXWARE_LLVM_MMIX_SIMCONFIG_H
